# Generated by Django 3.1 on 2020-08-19 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_place', models.CharField(max_length=20)),
                ('meet_place_select', models.CharField(choices=[('흑석', '흑석'), ('정문', '정문'), ('중문', '중문'), ('후문', '후문'), ('상도', '상도')], default='흑석', max_length=2)),
                ('meet_place_detail', models.CharField(max_length=20)),
                ('request_item', models.CharField(default='', max_length=50)),
                ('request_detail', models.TextField()),
                ('request_quantity', models.PositiveIntegerField(default=1)),
                ('fees', models.IntegerField(default=1000, verbose_name='Fees')),
                ('limited_time_hour', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='Hour')),
                ('limited_time_min', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)], verbose_name='Minute')),
                ('limited_time_sec', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)], verbose_name='Second')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
