# Generated by Django 3.1 on 2020-08-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_place', models.CharField(max_length=20)),
                ('meet_place', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('detail_request', models.TextField()),
                ('fees', models.TextField()),
            ],
        ),
    ]
