# Generated by Django 3.1 on 2020-08-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='limited_time_hour',
            field=models.IntegerField(default=0, verbose_name='number'),
        ),
        migrations.AddField(
            model_name='blog',
            name='limited_time_min',
            field=models.IntegerField(default=0, verbose_name='number'),
        ),
        migrations.AddField(
            model_name='blog',
            name='limited_time_sec',
            field=models.IntegerField(default=0, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(verbose_name='auto_now_add=True'),
        ),
    ]
