# Generated by Django 3.1 on 2020-08-13 06:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200813_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='meet_place',
            new_name='meet_place_detail',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='detail_request',
            new_name='request_detail',
        ),
        migrations.AddField(
            model_name='blog',
            name='meet_place_select',
            field=models.CharField(choices=[('흑석', '흑석'), ('정문', '정문'), ('중문', '중문'), ('후문', '후문'), ('상도', '상도')], default='흑석', max_length=2),
        ),
        migrations.AddField(
            model_name='blog',
            name='request_item',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='blog',
            name='request_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='blog',
            name='limited_time_hour',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='Hour'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='limited_time_min',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)], verbose_name='Minute'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='limited_time_sec',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)], verbose_name='Second'),
        ),
    ]
