# Generated by Django 3.1 on 2020-08-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='nickname',
            field=models.CharField(max_length=50, null=True, verbose_name='nickname'),
        ),
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=100, null=True, verbose_name='phone'),
        ),
        migrations.AddField(
            model_name='account',
            name='student_number',
            field=models.CharField(max_length=30, null=True, verbose_name='student_number'),
        ),
        migrations.AddField(
            model_name='account',
            name='university',
            field=models.CharField(max_length=50, null=True, verbose_name='university'),
        ),
    ]
