# Generated by Django 3.1 on 2020-08-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200820_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=100, null=True, verbose_name='전화번호'),
        ),
    ]
