# Generated by Django 3.1 on 2020-08-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200820_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=60, unique=True, verbose_name='학교 이메일'),
        ),
        migrations.AlterField(
            model_name='account',
            name='nickname',
            field=models.CharField(max_length=50, null=True, verbose_name='닉네임'),
        ),
        migrations.AlterField(
            model_name='account',
            name='student_number',
            field=models.CharField(max_length=30, null=True, verbose_name='학번'),
        ),
        migrations.AlterField(
            model_name='account',
            name='university',
            field=models.CharField(max_length=50, null=True, verbose_name='단과 대학'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='이름'),
        ),
    ]
