# Generated by Django 3.1 on 2020-08-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200820_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=60, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='account',
            name='nickname',
            field=models.CharField(max_length=50, null=True, verbose_name='nickname'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=100, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='account',
            name='student_number',
            field=models.CharField(max_length=30, null=True, verbose_name='student_number'),
        ),
        migrations.AlterField(
            model_name='account',
            name='university',
            field=models.CharField(max_length=50, null=True, verbose_name='university'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
