# Generated by Django 3.1 on 2020-08-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200827_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='photo_profil'),
        ),
    ]
